---
- hosts: all
  vars: 
  - msg1: "{{P1|default('No Message')}}"
  - msg2: "{{lookup('ansible.builtin.env', 'HOME')}}"
  tasks:
  - name: Print vars 
    debug: msg = "{{msg1}},{{msg2}}"

    
