---
- hosts: all
  vars: 
  - msg1: "{{P1|default('No Message')}}"
  - msg2: "{{lookup('ansible.builtin.env', 'HOME')}}"
  tasks:
  - name: Print vars 
    debug: 
      msg: "{{ msg2 }}"
  - name: Print vars 2
    debug: 
      msg: "{{msg2}}"

    
